name: Deploy to Render

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dasfadenkreuzjr
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Pull Docker image
        run: docker pull dasfadenkreuzjr/todoiscool:latest

      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}