name: Manual Release Build

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test 

      - name: Build Docker image
        run: docker build -t todo-is-cool:latest .

      - name: Save Docker image as tar
        run: docker save todo-is-cool:latest -o todo-is-cool.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: todo-is-cool.tar