name: Release Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t todo-is-cool:latest .

      - name: Tag Docker image for Docker Hub
        run: docker tag todo-is-cool:latest dasfadenkreuzjr/todoiscool:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dasfadenkreuzjr
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Push Docker image to Docker Hub
        run: docker push dasfadenkreuzjr/todoiscool:latest